title: Canonicum

description: Project documentation

show_downloads: false

theme: jekyll-theme-dinky

gems: [jekyll-mermaid]

#mermaid:
#  src: '/home/tlboyd/.local/share/Trash/files/myblog/node_modules/mermaid/dist/mermaid.js'

collections:
  documents:
    output: true

  techdocs:
    output: true
